# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Travis Houser
email: travis.w.houser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a tech enthusiast working to expand my knowledge in the Computer Science and Data Analytics fields. I enjoy reading, gaming, and programming.  I've worked mainly with Javascript, VBA, and Ruby, but I'm working hard each day to broaden my skillset.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://travishouser.net" # the base hostname & protocol for your site
twitter_username: TravisNotDoogie
github_username:  House of Codes

# Build settings
markdown: kramdown
